url:
#source: source #Changes the directory where Jekyll will look to transform files

pygments: true
paginate: 20
exclude: [dev, myblog.iml, CNAME, product.sh]
permalink: /:year/:month/:day/:title.html   #./:year-:month-:day/:title.html

markdown: redcarpet