url:
#source: source #Changes the directory where Jekyll will look to transform files

highlighter: pygments
paginate: 12
exclude: [dev, myblog.iml, CNAME, product.sh, bower_components, node_modules]
permalink: pretty # /:year/:month/:day/:title.html   #./:year-:month-:day/:title.html

markdown: redcarpet
